---
version: '3'

includes:
  ansible: ./.config/taskfiles/ansible/Taskfile.yml
  ansible:ansibler: ./.config/taskfiles/ansible/Taskfile-ansibler.yml
  ansible:test: ./.config/taskfiles/ansible/Taskfile-test.yml
  boilr: ./.config/taskfiles/Taskfile-boilr.yml
  common: ./.config/taskfiles/common/Taskfile.yml
  common:code: ./.config/taskfiles/common/Taskfile-code.yml
  common:update: ./.config/taskfiles/common/Taskfile-update.yml
  docker: ./.config/taskfiles/Taskfile-docker.yml
  fix: ./.config/taskfiles/Taskfile-fix.yml
  git: ./.config/taskfiles/Taskfile-git.yml
  image: ./.config/taskfiles/Taskfile-image.yml
  install: ./.config/taskfiles/Taskfile-install.yml
  lint: ./.config/taskfiles/lint/Taskfile.yml
  lint:esprint: ./.config/taskfiles/lint/Taskfile-esprint.yml
  lint:markdown: ./.config/taskfiles/lint/Taskfile-markdown.yml
  lint:prose: ./.config/taskfiles/lint/Taskfile-prose.yml
  nest: ./.config/taskfiles/nest/Taskfile.yml
  npm: ./.config/taskfiles/npm/Taskfile.yml
  npm:cov: ./.config/taskfiles/npm/Taskfile-cov.yml
  npm:doc: ./.config/taskfiles/npm/Taskfile-doc.yml
  packer: ./.config/taskfiles/Taskfile-packer.yml
  publish: ./.config/taskfiles/publish/Taskfile.yml
  publish:android: ./.config/taskfiles/publish/Taskfile-android.yml
  publish:brew: ./.config/taskfiles/publish/Taskfile-brew.yml
  publish:chrome: ./.config/taskfiles/publish/Taskfile-chrome.yml
  publish:firefox: ./.config/taskfiles/publish/Taskfile-firefox.yml
  publish:ios: ./.config/taskfiles/publish/Taskfile-ios.yml
  publish:menubar: ./.config/taskfiles/publish/Taskfile-menubar.yml
  publish:opera: ./.config/taskfiles/publish/Taskfile-opera.yml
  python: ./.config/taskfiles/Taskfile-python.yml
  security: ./.config/taskfiles/Taskfile-security.yml
  symlink: ./.config/taskfiles/Taskfile-symlink.yml
  upstream: ./.config/taskfiles/upstream/Taskfile.yml

  upstream:common: ./.config/taskfiles/upstream/Taskfile-common.yml
  upstream:docs: ./.config/taskfiles/upstream/Taskfile-docs.yml
  upstream:project: ./.config/taskfiles/upstream/Taskfile-project.yml
  vscode: ./.config/taskfiles/Taskfile-vscode.yml
output: interleaved

vars:
  GITHUB_ORG: ProfessorManhattan
  GITHUB_USER: ProfessorManhattan
  NPM_PROGRAM: npm
  NPX_PACKAGE: npx
  REPOSITORY_SUBTYPE: dockerfile
  REPOSITORY_TYPE: common
  TIMEZONE: America/New_York

tasks:
  donothing: 'true'

  start:
    desc: Set up the project and refresh it with the latest changes
    summary: |
      # Set up the project

      This task will scaffold the project with the latest upstream changes
      and ensure your development environment has all the dependencies installed.

      **Example usage:**
      `task start`
    cmds:
      - task: upstream:common
