---
stages:
  - update
  - fix
  - lint
  - test
  - security
  - publish

include:
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/fix/prettier-fix.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/lint/hadolint.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/lint/prettier.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/lint/shellcheck.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/publish/dockerhub.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/test/gitlab-registry.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/update/update-project.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

container_scanning:
  stage: security

dependency_scanning:
  stage: security

license_scanning:
  stage: security

.secret-analyzer:
  stage: security
