---
version: '3'

output: prefixed

vars:
  REPOSITORY_SUBTYPE: ansible-molecule
  REPOSITORY_TYPE: dockerfile

includes:
  common: ./.common/taskfiles-ansible-molecule/Taskfile-common.yml
  docker: ./.common/taskfiles-ansible-molecule/Taskfile-docker.yml
  fix: ./.common/taskfiles-ansible-molecule/Taskfile-fix.yml
  lint: ./.common/taskfiles-ansible-molecule/Taskfile-lint.yml
  software: ./.common/taskfiles-ansible-molecule/Taskfile-{{OS}}.yml
