---
version: '3'

includes:
  common: ./.common/taskfiles/common/Taskfile.yml
  common:update: ./.common/taskfiles/common/Taskfile-update.yml
  docker: ./.common/taskfiles/Taskfile-docker.yml
  fix: ./.common/taskfiles/Taskfile-fix.yml
  git: ./.common/taskfiles/Taskfile-git.yml
  image: ./.common/taskfiles/Taskfile-image.yml
  install: ./.common/taskfiles/Taskfile-install.yml
  lint: ./.common/taskfiles/Taskfile-lint.yml
  npm: ./.common/taskfiles/Taskfile-npm.yml
  security: ./.common/taskfiles/Taskfile-security.yml
  vscode: ./.common/taskfiles/Taskfile-vscode.yml

output: interleaved

vars:
  REPOSITORY_SUBTYPE: ci-pipeline
  REPOSITORY_TYPE: dockerfile

tasks:
  donothing: 'true'

  start:
    desc: Set up the project and refresh it with the latest changes
    summary: |
      # Set up the project

      This task will scaffold the project with the latest upstream changes
      and ensure your development environment has all the dependencies installed.

      **Example usage:**
      `task start`
    cmds:
      - task: common:update:update
